"""Re-exports for `from app.models import *` style imports.

Each module groups related tables; importing this package guarantees Alembic's
autogenerate sees every model.
"""

from app.models.agent import (
    Agent,
    AgentInvocation,
    AgentPrompt,
    AgentToolCall,
)
from app.models.anomaly import Anomaly
from app.models.equipment import Equipment, Inspection
from app.models.capa import (
    Capa,
    CapaAction,
    CapaAttachment,
    CapaComment,
    CapaContributor,
    CapaLinkage,
    CapaPatternGroup,
    CapaRootCause,
    CapaSlaProfile,
    CapaSourceCategory,
    CapaSourceType,
    CapaSubCategory,
    CapaVerificationMethod,
)
from app.models.competency_matrix import (
    Competency,
    CompetencyAssessment,
    CompetencyRecord,
    CompetencyRecordVersion,
    CompetencyValidationAttempt,
    PersonRoleAssignment,
    RecertificationCycle,
    RecertificationTask,
    RoleCompetencyRequirement,
    RoleDefinition,
    Skill,
    SupervisedPerformanceRecord,
)
from app.models.flra import FLRA, FLRACrewSignature, FLRAStatus, FLRATeamMember
from app.models.eai import (
    EaiAspect,
    EaiAspectCategory,
    EaiComplianceObligation,
    EaiEntry,
    EaiEntryAspect,
    EaiEntryControl,
    EaiEntryImpact,
    EaiEntryRecommendedControl,
    EaiEntryRegulationRef,
    EaiFeatureFlag,
    EaiReceptor,
    EaiRegulation,
    EaiReviewCycle,
    EaiStudy,
    EaiStudyTeamMember,
    EaiVersion,
    EnvironmentalImpactMatrix,
    EnvironmentalImpactMatrixCell,
    EnvironmentalImpactMatrixLikelihood,
    EnvironmentalImpactMatrixMagnitude,
)
from app.models.hira import (
    HiraCapa,
    HiraControl,
    HiraEntry,
    HiraEntryControl,
    HiraEntryHazard,
    HiraEntryRecommendedControl,
    HiraEntryRegulationRef,
    HiraHazard,
    HiraReviewCycle,
    HiraStudy,
    HiraStudyAttachment,
    HiraStudyTeamMember,
    HiraVersion,
    RiskMatrix,
    RiskMatrixCell,
    RiskMatrixLikelihood,
    RiskMatrixSeverity,
)
from app.models.incident import (
    Incident,
    IncidentAttachment,
    IncidentInvestigationMember,
    IncidentStatus,
    IncidentType,
)
from app.models.manhours import Manhours
from app.models.masters import ContractorCompany, Department, MasterItem
from app.models.near_miss import NearMiss, NearMissStatus
from app.models.near_miss_children import (
    NearMissAttachment,
    NearMissCapa,
    NearMissComment,
    NearMissPersonAffected,
    NearMissPersonInvolved,
    NearMissWitness,
)
from app.models.observation import (
    Observation,
    ObservationAttachment,
    ObservationCategory,
    ObservationStatus,
    ObservationType,
    Severity,
)
from app.models.permit import (
    Permit,
    PermitCrewMember,
    PermitStatus,
    PermitType,
)
from app.models.plant import Area, Plant
from app.models.ppe import (
    PpeBatch,
    PpeInspection,
    PpeIssuance,
    PpeItem,
    PpeRequirementProfile,
    PpeType,
)
from app.models.training import (
    TrainingAssessment,
    TrainingAssessmentResponse,
    TrainingAttendance,
    TrainingCertificate,
    TrainingProgram,
    TrainingProgramMaterial,
    TrainingProgramQuestion,
    TrainingRecord,
    TrainingRegistration,
    TrainingSchedule,
    TrainingSession,
)
from app.models.user import (
    Permission,
    Role,
    RolePermission,
    User,
    UserRole,
)
from app.models.workflow import (
    InstanceStatus,
    StepType,
    TaskStatus,
    TaskType,
    WorkflowDefinition,
    WorkflowDefinitionVersion,
    WorkflowHistory,
    WorkflowInstance,
    WorkflowStep,
    WorkflowTask,
)

__all__ = [
    "Agent",
    "AgentInvocation",
    "AgentPrompt",
    "AgentToolCall",
    "Anomaly",
    "Area",
    "Capa",
    "CapaAction",
    "Competency",
    "CompetencyAssessment",
    "CompetencyRecord",
    "CompetencyRecordVersion",
    "CompetencyValidationAttempt",
    "PersonRoleAssignment",
    "RecertificationCycle",
    "RecertificationTask",
    "RoleCompetencyRequirement",
    "RoleDefinition",
    "Skill",
    "SupervisedPerformanceRecord",
    "CapaAttachment",
    "CapaComment",
    "CapaContributor",
    "CapaLinkage",
    "CapaPatternGroup",
    "CapaRootCause",
    "CapaSlaProfile",
    "CapaSourceCategory",
    "CapaSourceType",
    "CapaSubCategory",
    "CapaVerificationMethod",
    "Equipment",
    "FLRA",
    "FLRACrewSignature",
    "FLRAStatus",
    "FLRATeamMember",
    "HiraCapa",
    "HiraControl",
    "HiraEntry",
    "HiraEntryControl",
    "HiraEntryHazard",
    "HiraEntryRecommendedControl",
    "HiraEntryRegulationRef",
    "HiraHazard",
    "HiraReviewCycle",
    "HiraStudy",
    "HiraStudyAttachment",
    "HiraStudyTeamMember",
    "HiraVersion",
    "RiskMatrix",
    "RiskMatrixCell",
    "RiskMatrixLikelihood",
    "RiskMatrixSeverity",
    "Incident",
    "IncidentAttachment",
    "IncidentInvestigationMember",
    "IncidentStatus",
    "IncidentType",
    "Inspection",
    "InstanceStatus",
    "Manhours",
    "NearMiss",
    "NearMissStatus",
    "Observation",
    "ObservationAttachment",
    "ObservationCategory",
    "ObservationStatus",
    "ObservationType",
    "Permission",
    "Permit",
    "PermitCrewMember",
    "PermitStatus",
    "PermitType",
    "Plant",
    "PpeBatch",
    "PpeInspection",
    "PpeIssuance",
    "PpeItem",
    "PpeRequirementProfile",
    "PpeType",
    "Role",
    "RolePermission",
    "Severity",
    "StepType",
    "TaskStatus",
    "TaskType",
    "TrainingAssessment",
    "TrainingAssessmentResponse",
    "TrainingAttendance",
    "TrainingCertificate",
    "TrainingProgram",
    "TrainingProgramMaterial",
    "TrainingProgramQuestion",
    "TrainingRecord",
    "TrainingRegistration",
    "TrainingSchedule",
    "TrainingSession",
    "User",
    "UserRole",
    "WorkflowDefinition",
    "WorkflowDefinitionVersion",
    "WorkflowHistory",
    "WorkflowInstance",
    "WorkflowStep",
    "WorkflowTask",
]
